function getObjTerce() {
  return {
    ubicacion: "",
    direct: "",
    subdirect: "",
    codigo: "",
    descrip: "",
    direcc: "",
    dv: "",
    zona: "",
    ruta: "",
    orden: "",
    bloq: "",
    tipo: "",
    tipoR: "",
    grado: "",
    calific: "",
    regIva: "",
    rut: "",
    convenio: "",
    plazo: "",
    telefono: "",
    nit: "",
    act: "",
    vendedor: "",
    entidad: "",
    retenedor: "",
    factor: "",
    codCiu: "",
    pago: "",
    exent: "",
    retIva: "",
    marcaVeh: "",
    empresaVeh: "",
    nroVeh: "",
    placaVeh: "",
    fechaAlinVeh: "",
    fechaNac: "",
    cant: "",
    cupo: "",
    refer1: "",
    refer2: "",
    refer3: "",
    cargo: "",
    seguro: "",
    datacre: "",
    fechaCre: "",
    apel1: "",
    apel2: "",
    nomb1a: "",
    nomb1b: "",
    nomRef1: "",
    dirRef1: "",
    telRef1: "",
    relRef1: "",
    nomRef2: "",
    dirRef2: "",
    telRef2: "",
    relRef2: "",
    nomRef3: "",
    dirRef3: "",
    telRef3: "",
    relRef3: "",
    nomTrab: "",
    dirTrab: "",
    telTrab: "",
    carTrab: "",
    sueTrab: "",
    antTrab: "",
    ciuExp: "",
    entidAfi: "",
    fechaAfi: "",
    emailTer2: "",
    granContrib: "",
    retIvaCompra: "",
    activIca: "",
    embargos: "",
    porcIca: "",
    extraCupo: "",
    acuePago: "",
    idReprLegal: "",
    reprLegal: "",
    idTesor: "",
    tesorero: "",
    emailRep: "",
    emailtes: "",
    capitado: "",
    tipoCupo: "",
    indicativo: "",
    asesor: "",
    nit1Cli: "",
    retIcav: "",
    adminMod: "",
    fechaMod: "",
    procesoMod: "",
    admiCre: "",
    regWeb: "",
    porcEstamp: "",
    email: "",
    descripCont: "",
    telCont: "",
    emailCont: "",
    proced: "",
    destino: "",
    nacional: "",
    habit: "",
    pasaport1: "",
    pasaport2: "",
    tablaAcomp: [
      {
        nombreAcomp: "",
        tipoIdAcomp: "",
        expIdAcomp: "",
        identAcomp: "",
        nacionAcomp: "",
      },
    ],
    tablaDirecciones: [
      {
        direccionExt: "",
        codCiuExt: "",
        telefonoExt: "",
        barrio: "",
      },
    ],
    nomComer: "",
    estado: "",
    exiva: "",
    fechaVfact: "",
    sucUfact: "",
    nroUfact: "",
    porcRet: "",
    vlrBaseRet: "",
    codVtas: "",
    clasificacion: "",
    orderReference: "",
    frecuencia: "",
    ordenRuta: "",
    contrato: "",
    activida: "",
    autorizacion: "",
  };
}

function getObjTerce_() {
  return {
    codigo: {
      id: "codigo",
      label: "Codigo",
      max_length: "10",
      disabled: true,
      required: true,
      f8: true,
    },
    tipoR: {
      id: "tipoR",
      label: "Tipo identificación",
      items: [
        { id: 1, text: "1 - CC - CEDULA CIUDADANIA" },
        { id: 2, text: "2 - CE - CEDULA EXTRANJEA" },
        { id: 3, text: "3 - PA - NUMERO PASAPORTE" },
        { id: 4, text: "4 - RC - REGISTRO CIVIL" },
        { id: 5, text: "5 - TI - TARJETA DE IDENTIDAD" },
        { id: 6, text: "6 - NU - NUMERO UNICO DE IDENTIDAD" },
        { id: 7, text: "7 - NI - NUMERO IDENTIDAD TRIBUTARIA N" },
      ],
      item_value: "id",
      disabled: true,
    },
    nomb1a: {
      id: "nomb1a",
      label: "Primer nombre",
      max_length: "30",
      required: true,
      disabled: true,
    },
    nomb1b: {
      id: "nomb1b",
      label: "Segundo nombre",
      max_length: "30",
      required: true,
      disabled: true,
    },
    apel1: {
      id: "apel1",
      label: "Primer apellido",
      max_length: "30",
      required: true,
      disabled: true,
    },
    apel2: {
      id: "apel2",
      label: "Segundo apellido",
      max_length: "30",
      required: true,
      disabled: true,
    },
    direcc: {
      id: "direcc",
      label: "Dirección",
      max_length: "30",
      required: true,
      disabled: true,
    },
    telefono: {
      id: "telefono",
      label: "Telefono",
      max_length: "10",
      tipo: "number",
      required: true,
      disabled: true,
    },
    email: {
      id: "email",
      label: "Email",
      max_length: "50",
      tipo: "email",
      required: true,
      disabled: true,
    },
  };
}
export { getObjTerce_, getObjTerce };
