function getObjRegFact() {
  return {
    llave: {
      suc: "",
      cl: "",
      nro: "",
    },
    fecha: {
      anio: "",
      mes: "",
      dia: "",
    },
    cta: {
      prefijo: "",
      nro_cta: "",
    },
    nit: "",
    id_historia: "",
    descrip_id_historia: "",
    fecha_ing_estad: {
      anio: "",
      mes: "",
      dia: "",
    },
    tabla: JSON.parse(
      JSON.stringify(
        Array(140).fill({
          alm: "",
          grupo: "",
          cod_art: "",
          clase_art: "",
          descrip: "",
          cod_lote: "",
          lote_medipow: "",
          cant: "",
          vlr: "",
          dias_trata: "",
          vlr_resul: "",
          vlr_interp: "",
          vlr_later: "",
        })
      )
    ),
    valor_des: "",
    tipo_copago: "",
    copago_estim: "",
    vlr_iva: "",
    medicos: {
      med_cir: "",
      med_cir_descrip: "",
      med_ayu: "",
      med_ayu_descrip: "",
      med_ane: "",
      med_ane_descrip: "",
      med_ins: "",
      med_ins_descrip: "",
      med_otr: "",
      med_otr_descrip: "",
    },
    datos_cir: {
      via: "",
      mult: "",
      nro_cir: "",
      cruenta: "",
      grupo_cir: "",
      fac_labser: "",
    },
    puerta_estad: "",
    tarif: "",
    costo: "",
    costo_nombre: "",
    espec_elab: "",
    espec_elab_descrip: "",
    detalle: "",
    control_cap_estad: "",
    nro_autor_elab: {
      pref: "",
      comp: "",
      resto: "",
    },
    control_mes: "",
    f_pago: "",
    bloqueo_imp: "",
    nro_form: {
      ind_form: "",
      nro_ped: "",
    },
    cama_rx: "",
    oper_elab: "",
    fecha_elab: {
      anio: "",
      mes: "",
      dia: "",
    },
    hora_elab: {
      hr: "",
      mn: "",
    },
    hora_aten_estad: {
      hr: "",
      mn: "",
    },
    oper_correc: "",
    fecha_correc: {
      anio: "",
      mes: "",
      dia: "",
    },
    hora_correc: {
      hr: "",
      mn: "",
    },
    unid_edad_elab: "",
    vlr_edad_elab: "",
    causa_estad: "",
    embar_estad: "",
    personal_elab: "",
    clase_proc_estad: "",
    tipo_proc_estad: "",
    cod_serv_estad: "",
    finalid_estad: "",
    triage_estad: "",
    tip_diag_estad: "",
    repetid_estad: "",
    tabla_diag_estad: JSON.parse(
      JSON.stringify(
        Array(10).fill({
          cod: "",
          descrip: "",
        })
      )
    ),
    hor_obser_estad: "",
    dias_inc_estad: "",
    tipo_discap_elab: "",
    grado_discap_elab: "",
    estad_sal_estad: "",
    fecha_sal_estad: {
      anio: "",
      mes: "",
      dia: "",
    },
    hora_salid_estad: {
      hr: "",
      mn: "",
    },
    diag_muer_estad: "",
    remite: "",
    espec_remi: "",
    unserv: "",
    tipo_dr: "",
    birads: "",
    macro: "",
    ult_examen_estad: {
      anio: "",
      mes: "",
      dia: "",
    },
    complejidad: "",
    cup_paq_int: "",
    ordserv: {
      pref_ordserv: "",
      cl_ordserv: "",
      nro_ordserv: "",
    },
    fecha_entr_rx: {
      anio: "",
      mes: "",
      dia: "",
    },
    hora_entr_rx: {
      hr: "",
      mn: "",
    },
    recibido_rx: "",
    oper_entr_rx: "",
    cronico: "",
    destino_refact: "",
    refactura: "",
    oper_corr_rips: "",
    fecha_corr_rips: {
      anio: "",
      mes: "",
      dia: "",
    },
    recibido2_rx: "",
    mot_bloqueo_rx: "",
    datos_4505: {
      sintom_respi: "",
      _1ra_vez: "",
      planific: "",
      fecha_parto_fur: {
        anio: "",
        mes: "",
        dia: "",
      },
      talla: "",
      peso: "",
      nro_cont_pren: "",
      fluorosis: "",
      calid_muest: "",
      edad_gest: "",
      sintom_piel: "",
      victi_maltrato: "",
      victi_violencia: "",
      enfer_mental: "",
      form_auto: "",
      despac_for_auto: "",
      oper_despac_for: "",
      tens1: "",
      tens2: "",
    },
    pendiente: "",
    nro_pendi: {
      suc_pendi: "",
      cl_pendi: "",
      num_pendi: "",
    },
    fecha_pendi: {
      anio: "",
      mes: "",
      dia: "",
    },
    hora_pendi: {
      hr: "",
      mn: "",
    },
    nro_entrependi: {
      suc_entrependi: "",
      cl_entrependi: "",
      num_entrependi: "",
    },
    fecha_entrependi: {
      anio: "",
      mes: "",
      dia: "",
    },
    hora_entrependi: {
      hr: "",
      mn: "",
    },
    cant_pendi: "",
    tipo_pendi: "",
    fact_auto: "",
    vlr_iva1: "",
    vlr_iva2: "",
    vlr_iva3: "",
    gest_riesg: "",
    gest_gesta: "",
    gest_croni: "",
    consec_barras: "",
    datos_4505_2: {
      empac_for_auto: "",
      total_desc: "",
      total_sindes: "",
      agud_visual_oi: {
        agud_visual_oi_1: "",
        agud_visual_oi_2: "",
      },
      agud_visual_od: {
        agud_visual_od_1: "",
        agud_visual_od_2: "",
      },
      calc_msne_fin: "",
      calc_vale: "",
    },
    hemo_glicosilada: "",
    hemo_glico_fecha: {
      anio: "",
      mes: "",
      dia: "",
    },
    fecha_microalbuminuria: {
      anio: "",
      mes: "",
      dia: "",
    },
    microalbuminuria2: "",
    creatinina2: "",
    fecha_creatinina: {
      anio: "",
      mes: "",
      dia: "",
    },
    tipo_pago: "",
    etapa_vacuna: "",
    tipo_vacuna: "",
    nro_dosis: "",
    tipoetapa_vacuna: "",
    var_cop: {
      sanos_cop: "",
      caries_nocavi_cop: "",
      caries_cavi_cop: "",
      obtura_cop: "",
      ausente_cop: "",
      nro_dient_cop: "",
    },
    punt_escala_abrev: {
      pt_tipica_mg: "",
      pt_tipica_mf: "",
      pt_tipica_ps: "",
      pt_tipica_al: "",
    },
    fecha_limi_auto: {
      anio: "",
      mes: "",
      dia: "",
    },
    ord_salida: {
      per_salida: "",
      nro_salida: "",
    },
    orig_rips: "",
    upc: "",
    tab_usuar_capit: JSON.parse(
      JSON.stringify(
        Array(10).fill({
          nro_usuar_capit: "",
        })
      )
    ),
    fecha_accid_rips: {
      anio: "",
      mes: "",
      dia: "",
    },
    empresa_paci_rips: "",
    fecha_presen: {
      anio: "",
      mes: "",
      dia: "",
    },
    med_tec: "",
    med2_rx: "",
    ciudad: "",
    observ_rips: "",
    motivo_consul_rips: "",
    tabla_abon_salud: JSON.parse(
      JSON.stringify(
        Array(10).fill({
          fecha_abon_salud: {
            anio: "",
            mes: "",
          },
          secu_abon_salud: {
            lote_abon_salud: "",
            comp_abon_salud: "",
            item_abon_salud: "",
          },
          vlr_abon_salud: "",
        })
      )
    ),
  };
}

function getObjRegFact_() {
  return {
    suc: {
      id: "suc",
      label: "Sucursal",
      placeholder: "Insertar sucursal",
      max_length: "2",
      disable: true,
      require: true,
      f8: " true",
    },
    cl: {
      id: "cl",
      label: "Clase ",
      placeholder: "Insertar clase de servicio",
      max_length: "1",
      disable: true,
      require: true,
      f8: " true",
    },
    cl2: {
      id: "cl",
      label: "Servicio ",
      placeholder: "Clase de servicio",
      max_length: "1",
      disable: true,
      require: true,
      // f8: " true",
    },
    nro: {
      id: "nro",
      label: "Comprobante",
      placeholder: "Insertar numero comprobante",
      max_length: "6",
      disable: true,
      require: true,
      f8: " true",
    },
  };
}

export { getObjRegFact, getObjRegFact_ };
